name: toriis
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy=1.23.5 
  - openpyxl=3.1.1
  - pandas=1.5.3
  - pymongo=4.3.3
  - python=3.9.0
  - requests=2.28.2
  - yfinance=0.2.12=pyhd8ed1ab_0
